#!/bin/bash
USER=""
PW=""

apt-get -q update

#Noninteractive phpmyadmin configuration
export DEBIAN_FRONTEND='noninteractive'
echo -e "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo -e "phpmyadmin phpmyadmin/app-password-confirm password $PASS" | debconf-set-selections
echo -e "phpmyadmin phpmyadmin/mysql/admin-pass password $PASS" | debconf-set-selections
echo -e "phpmyadmin phpmyadmin/mysql/app-pass password $PASS" | debconf-set-selections
echo -e "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections

#Install the actual phpmyadmin
apt-get install -y phpmyadmin php-mbstring php-gettext

#Enable the Php extension
sudo phpenmod mcrypt
sudo phpenmod mbstring

service apache2 restart

echo -e "Phpmyadmin installed" >> /var/log/$USERLogs
