#!/bin/bash
USER='tmd11a'
PASS='Myles'
IP='104.219.55.210'

#Need to install unzip to get Sugar
apt-get -y install unzip
#Install Php apps if not already installed
apt-get -y install imagemagick php7.0-curl php7.0-gd php7.0-mbstring php7.0-mysql libapache2-mod-php7.0 php7.0-mcrypt php7.0-bz2 php7.0-zip php7.0-json php7.0-xsl php7.0-imap php7.0-common php7.0-dev php7.0-cli  php7.0-imap php7.0-xmlrpc

#Change the max filesize PHP can handle
sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 16M/' /etc/php/7.0/apache2/php.ini
sed -i 's/post_max_size = 8M/post_max_size = 24M/' /etc/php/7.0/apache2/php.ini

phpenmod imap
phpenmod zip
phpenmod mbstring

mkdir /var/www/html/sugar
mkdir /tmp/sugar

#Get Sugar zip in tmp, and unzip it to its own directory
cd /tmp
wget -O sugar.zip http://sourceforge.net/projects/sugarcrm/files/latest/download
unzip -q /tmp/sugar.zip -d sugar

cp -R /tmp/sugar/SugarCE-Full-6.5.25/* /var/www/html/sugar
chmod 775 -R /var/www/html/sugar
chown -R www-data:www-data /var/www/html/sugar


#Create database for Sugar/Suite
mysql -e "CREATE DATABASE sugar;"
mysql -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON sugar.* TO '$USER'@'%' IDENTIFIED BY '$PASS';"
mysql -e "FLUSH PRIVILEGES;"

touch /var/www/html/sugar/config_si.php
cat <<EOF > /var/www/html/sugar/config_si.php
<?php
\$sugar_config_si  = array (
    'dbUSRData' => 'create',
    'default_currency_iso4217' => 'USD',
    'default_currency_name' => 'US Dollar',
    'default_currency_significant_digits' => '2',
    'default_currency_symbol' => '$',
    'default_date_format' => 'Y-m-d',
    'default_decimal_seperator' => '.',
    'default_export_charset' => 'ISO-8859-1',
    'default_language' => 'en_us',
    'default_locale_name_format' => 's f l',
    'default_number_grouping_seperator' => ',',
    'default_time_format' => 'H:i',
    'export_delimiter' => ',',
    'setup_db_admin_password' => Myles,
    'setup_db_admin_user_name' => root,
    'setup_db_create_database' => 0,
    'setup_db_database_name' => sugar
    'setup_db_drop_tables' => 0,
    'setup_db_host_name' => localhost,
    'setup_db_pop_demo_data' => false,
    'setup_db_type' => mysql,
    'setup_db_username_is_privileged' => true,
    'setup_site_admin_password' => Myles,
    'setup_site_admin_user_name' => tmd11a,
    'setup_site_url' => IT410-Tmd11a,
    'setup_system_name' => Sugar-Tmd11a,
  );
EOF

VAR=$(sudo -u www-data curl -s http://$IP/sugar/install.php?goto=SilentInstall&cli=true)



echo -e "--\nSugar Installed" >> /var/log/tmd11aLogs

service apache2 restart
